### ISSUE TITLE
outreach with workantile

### ISSUE THREAD

**Issue by mrbobbytables** [orchestructure/presentations#1]
http://workantile.com/

Local downtown Ann Arbor community for remote and/or self-employed people. It might be an ideal group to contact regarding meeting space, speakers, or just get the word out regarding orchestructure.

**Comment by InAnimaTe** [comment]
Meeting with Ed this week actually at the Workantile; he works there on a regular basis. Will report more post-meeting.

**Comment by InAnimaTe** [comment]
^See #6 for more information about our planning of Ed to present here for one month soon. Regarding getting the word out, this can be approached after hosting there.

**Comment by mrbobbytables** [comment]
Closing this in favor of #6
