### ISSUE TITLE
Talk from Chris @ Little Caesars on their Infrastructure

### ISSUE THREAD

**Issue by InAnimaTe** [orchestructure/presentations#15]
And of course, they should probably provide Pizza ;)

**Comment by cscheib** [comment]
@InAnimaTe Jorge just reached out to me again today.  I was thinking I may be able to do a talk on RabbitMQ, including some of our lessons learned, and present my best practice recommendations.

I could probably do September, summer's likely to be busy for me.

**Comment by InAnimaTe** [comment]
Perfect! Definitely feel free to talk more about the underlying infra as I'm sure many will be quite interested. 

Let's plan for September then! Jorge or myself will ping you as it gets closer.

We really appreciate and look forward to hosting you!
