### ISSUE TITLE
Lightning Talk Idea: Home Infrastructure

### ISSUE THREAD

**Issue by jeefy** [orchestructure/presentations#16]
5-10 min demo on my local infrastructure

Kubernetes hosting:
Local DNS using Pi-Hole
Lan Cache (games + apt + pypi + docker)
Media tools (couchpotato, sickrage, transmission, sabnzbd, emby)
Gogs (Git Management)
Drone (CI Pipeline)

**Comment by InAnimaTe** [comment]
Approved! Want to do at the next meeting?

**Comment by jeefy** [comment]
Humm, if no one else is lined up I can. I was thinking of doing Feb's, but there isn't really a presentation to write, it's  "Watch me VPN home and show and tell"

So I'm game for whenever

**Comment by InAnimaTe** [comment]
Let's do tomorrow then. I don't have one planned yet so you can be the first lightning talk ever!

**Comment by InAnimaTe** [comment]
Just wanted to update: Jeff is going to to do this at the February meeting as he had some internet issues at the Jan. meeting.
