### ISSUE TITLE
Presentation from Andrew Sardone on Censys Infra

### ISSUE THREAD

**Issue by InAnimaTe** [orchestructure/presentations#17]
[Message](https://madeina2.slack.com/archives/C1GMM9R7V/p1516914550000055?thread_ts=1516914380.000742&cid=C1GMM9R7V) from Sardone talking about interest in speaking about the infra behind they're new startup: [Censys](https://censys.io/about)

**Comment by mrbobbytables** [comment]
Presented in July. Closing issue.
