### ISSUE TITLE
Talk from Nicholas Klick on Serverless with AWS

### ISSUE THREAD

**Issue by InAnimaTe** [orchestructure/presentations#19]
Nick reached out and is interested in doing another talk!

> I want to propose to give a talk on "Serverless Applications on AWS" based on a project I recently completed. Essentially, I am leveraging AWS Lambda Functions, SQS. etc as part of a request failover system. I could feasibly demo how to set it up using either cloudformation and/or terraform.

Let's nail down a location and get this planned!

**Comment by malaproping** [comment]
If that July 25th slot is still open, that works for me. Looking forward to it!

**Comment by InAnimaTe** [comment]
Sure is and reserved specifically for you!

**Comment by malaproping** [comment]
Much appreciated! See you at a meeting sometime in the near future. Thanks for organizing.

**Comment by mrbobbytables** [comment]
Presented in August. Closing Issue.

Thanks again!
