### ISSUE TITLE
@bdimcheff on Olark's infra

### ISSUE THREAD

**Issue by InAnimaTe** [orchestructure/presentations#21]
Would love to get [Brandon](http://brandon.dimcheff.com/) in to do a talk or lightning talk on Olark's journey to k8s relating to CI/CD and stateful applications.

**Comment by bdimcheff** [comment]
Here's some options:

* Followup on my devops days detroit/kubecon talk in 2016 on Olark's migration from Rackspace to GCP aka "what really happened cuz definitely it didn't go exactly as planned"
* Our CI/CD stuff that we built out of helm and gitlab CI (this one is probably shorter and lightning talk material)
* Adventures in hosting a stateful app that requires sticky sessions on kubernetes (this one might also be on the short side)

**Comment by InAnimaTe** [comment]
Why not all of them across different months!? (They all sound really good!) The second 2 seem shorter to present them as lightning talks over Feb and March.

The follow up talk can be longer and more dense. Plus, you can take time to mold it and we can plan for later this year (since we're already booked pretty far out)

Of course it's completely up to you, and you could even ask at the next meeting or in Slack what the members would prefer.

**Comment by mrbobbytables** [comment]
Bit out of date now XD maybe in new year on new infrastructure?
