### ISSUE TITLE
Chris Short presenting for January

### ISSUE THREAD

**Issue by InAnimaTe** [orchestructure/presentations#3]
Talked with Chris at the end of 17' and he was super interested in doing a presentation. He has many good ones that he can cherry pick from. I also suggested a slight twist which he liked:

> I like your lightning talk from gophercon. I think touting the usability and simpleness of Go would be good. I also like your devops readme lightning talk but instead of just books, maybe talking about other resources as well. Maybe some sort of combination of these two where you talk about how "traditional Ops" guys can slowly get into the "Dev" side of a modern DevOps position? i.e. `An Approach to Dev from an Ops' Perspective: Resources and playing with Go`

The January meeting would fall on the 31st of the month. I will also be opening up the floor to 2-5 minute lightning talks, among other announcements ;)

Lets use this thread to finish getting this presentation planned out and I'll make the meetup event.

**Comment by chris-short** [comment]
I do love the blending of talks idea. I need to cobble together an outline though to make sure it'll fit in the 20-30 minute time slot.

**Comment by InAnimaTe** [comment]
For sure. If it needs to extend a bit longer like 40 minutes, that's ok. As long as there is enough material to keep everyone sufficiently engaged for that long. Also, taking questions throughout the presentation will help keep it interactive.

**Comment by InAnimaTe** [comment]
@chris-short there's a lot of talk around your Docker is Dead post...you'll most certainly want to talk about (maybe in a lightning talk capacity) and get asked about it. Definitely be sure to talk about DevOps'ish as well.

@mrbobbytables any updates on a definitive location?

**Comment by mrbobbytables** [comment]
We are good to use the Solution zone for this month.

**Comment by InAnimaTe** [comment]
That is fantastic news! @chris-short I just need a presentation title and short desc. and I can post the meetup.

**Comment by InAnimaTe** [comment]
The meetup has been posted: https://www.meetup.com/orchestructure/events/246812066/

Working with Chris to iron out the presentation details and will update the meetup with it. Going to close.
