### ISSUE TITLE
I have two topics that I could present on.

### ISSUE THREAD

**Issue by mmclane** [orchestructure/presentations#38]
1. An automated terraform pipeline for Azure
We have completely automated our terraform pipeline for building resources in Azure.  This presentation will detail how our pipeline works at each stage: presubmit validation checks, deployment to preprod using terraform, inspec validation, deployment to production, etc.  Tools include Jenkins, Gerrit, Scripts, Terraform, Azure, and Inspec.  The intent is to have a demo heavy presentation and show some of the code behind what we are doing, some of the challenges we faced, and plans for future enhancements.  I want the audience to walk away from this presentation with ideas that they can take back and implement for themselves.

2. Lessons learned moving from AWS to Azure
My team has had to make the shift from working with AWS to embracing Azure.  This talk would be able the lessons we have learned so far.  The good, the different, and the frustrating.  The goal is to have people going way with glimpse into a the different cloud providers and the journey we have gone on.

**Comment by mrbobbytables** [comment]
We're currently booked through October, but either presentation sounds like a great topic. Would you be up for possibly presenting in November (28th)?

**Comment by mmclane** [comment]
I sure can.

**Comment by mrbobbytables** [comment]
Presentation scheduled for November. Closing Issue.

Thanks!
