### ISSUE TITLE
Meetup swag 

### ISSUE THREAD

**Issue by jeefy** [orchestructure/presentations#53]
Thinking about swag, not just for the meetup but for this/next year. Would like to hear thoughts. @orchestructure/board -- Also, I have neither bank info, nor a high-res logo copy. So I can line up what we get, but someone else will have to execute (or also just hook me up, I'm impartial)

## Attendees

Besides stickers (which we should ensure we're stocked on)

$136 for 250 Pens Single color w/ logo on one side 
https://www.discountmugs.com/product/bp320-customizable-black-ink-plastic-pens/

Coasters are single-use. Lots of other "conference swag" is cliche. I feel like pens are both useful hand-outs as well as decent promotional stuff. I can be swayed but I wasn't digging a lot of other things.

## Speakers

$252.28 for 24 stainless steel tumblers single color w/ logo on one side
https://www.discountmugs.com/product/11-oz-harbor-stainless-steel-stemless-wine-glasses/

With the speaker gifts, each of these tumblers is $10.50. I'd propose, as part of speaker coordination, asking whether they prefer coffee, tea, soda, ??? and then include a bit of that in as well.

Lastly, I feel each speaker gift should get a small thank you note written by one of us (and I'd go the extra mile and make them unique per person)

**Comment by InAnimaTe** [comment]
Yes, Yes, and Yes.

I'm good on pens. I also agree they are actually super useful and you can never have enough of them. We're good on stickers still as I have two unopened packs.

Tumblers is a great idea. 24 will keep us going for a while as well. Also love the personal note written by one of us; should also be signed by all of us. 

I'm good with you moving forward on design for both these things. We can work through chat to verify we like what we see and get the order placed. Nice work.

**Comment by jeefy** [comment]
Swag order placed. Once we receive/approve the proofs, I'll close this one out. :)

**Comment by jeefy** [comment]
Proofs approved, order is out. :)
